### PR TITLE
update for equipment's properties of zh-CN

### PR DESCRIPTION
**Pull request by ZhiGuoZheng**
Hi, jtborn:
Since the zh-CN version has not been updated for a long time, I just updated the properties of some items of zh-CN, and its value is based on the en-US.
And I'll update the set2 items later.
..........
The information for set2 has been updated.

### CODE REVIEW

**Comment by jtborn** [comment]
Thank you! I will merge these in later when I'm off work. :)

**Comment by ZhiGuoZheng** [comment]
> Thank you! I will merge these in later when I'm off work. :)

Thx bro~

**Comment by jtborn** [comment]
Sorry I was a little late. I just released Set 2. Unfortunately I didn't have the new items in the CN.xaml before but I copied them over in English so they can be translated. They're just the spatula item changes.

**Comment by jtborn** [comment]
I deleted the set2Preparations branch since it's officially released now so you can commit changes to Master. Thanks

**Comment by ZhiGuoZheng** [comment]
Ok, I will translate it later.

jtborn <notifications@github.com> 于2019年11月7日周四 下午1:26写道：

**Pull request closed without merging**
