### PR TITLE
Update ItemStrings_zh-CN.xaml

### PR DESCRIPTION
**Pull request by SuTree**
Update something according to Chinese service data.

There are still some Item data problems, and now there is no game playing, so I can't confirm. But I think this is not a big problem.

Thank you very much for updating.

### CODE REVIEW

**Comment by jtborn** [comment]
Thanks, I will merge this in and release new version tonight.
Edit: Sorry, got home late and forgot to update. I will fix it tonight.

**Comment by jtborn** [comment]
I merged in your changes but I believe the values for 肃静, 钢铁烈阳之匣, and 巨型九头蛇 were not correct. Can you confirm in client? Those values do not match NA values and I thought we had the same patch values.

**Comment by SuTree** [comment]
> I merged in your changes but I believe the values for 肃静, 钢铁烈阳之匣, and 巨型九头蛇 were not correct. Can you confirm in client? Those values do not match NA values and I thought we had the same patch values.

I refer to some app values are wrong, I need to go to the game to confirm. Wait until I have a rest at night to check it out. 

So I should confirm the value before submitting. I so sorry.

TitanicHydra ”巨型九头蛇“ only have 3% hurt, I didn't think about it, this Item is too low cost.

**Comment by SuTree** [comment]
I played the game and confirmed that the 2.22 version of the data is correct. 

However, there are still some items that are not official names in China client, and I will submit the merger after verification. Just some name questions, you can wait for the 9.23 version to be updated.

**Comment by jtborn** [comment]
Thank you! I appreciate your help! :)

**Pull request closed without merging**
