### PR TITLE
Update  Resource/Localization/ItemStrings_zh-CN.xaml 

### PR DESCRIPTION
**Pull request by Rumour999**
Checked the text being used, Some text hasn't been updated for a long time.

### CODE REVIEW

**Comment by jtborn** [comment]
Thanks for the update! I will add these and send out a new version tonight.

**Comment by Rumour999** [comment]
Why hasn't the file changed? An incorrect folder was added to the root…

**Comment by jtborn** [comment]
Sorry about that. That's what I get for auto-merging using GitHub instead of doing it manually. I updated the CN lang file yesterday for the Patch 10.2 updates and I guess I must've overwritten the file. I could've sworn I pulled first but oh well. I will manually merge in your updates tonight. Thanks for the heads up.

**Comment by jtborn** [comment]
Should be fixed now.

**Comment by Rumour999** [comment]
thx, but the file has updated the contents of version 10.2, which has not been updated in mainland China, I'll be back in a short while.
and…you have not deleted the wrong folder in the project root directory……

**Comment by jtborn** [comment]
Ahh that explains the whole thing. When I merged your branch change in I thought it was modifying the correct -CN.xml I didn't notice your branch had a new folder. Sorry about the 10.2 I figured I'd update it so someone else wouldn't have to do the Chinese update. I thought Riot released all patches worldwide at the same time. I'll just stick to the English version from now on and let you or someone else take care of the Chinese file. :)

**Comment by Rumour999** [comment]
OK, Now China is celebrating the Spring Festival, so Tencent will not update 10.2 version. Next time I update is still fork project and submit a pull request?(should be no more wrong folders…)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jtborn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月26日(星期天) 上午9:45
收件人:&nbsp;"jtborn/TFT-Overlay"<TFT-Overlay@noreply.github.com&gt;;
抄送:&nbsp;"没头脑和不高兴"<525482009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jtborn/TFT-Overlay] Update  Resource/Localization/ItemStrings_zh-CN.xaml  (#18)




Ahh that explains the whole thing. When I merged your branch change in I thought it was modifying the correct -CN.xml I didn't notice your branch had a new folder. Sorry about the 10.2 I figured I'd update it so someone else wouldn't have to do the Chinese update. I thought Riot released all patches worldwide at the same time. I'll just stick to the English version from now on and let you or someone else take care of the Chinese file. :)

**Comment by jtborn** [comment]
Yes, that should be good. I will make sure I double check it next time either way to make sure. Thanks for your help.

**Pull request merged**
